include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
analyzer:
  exclude:
    - build/**
    - '**/*.freezed.dart'
    - '**/*.g.dart'
##    - lib/src/service/model/**
  errors:
    invalid_annotation_target: ignore