name: space_backend
description: An new Dart Frog application
version: 0.0.1+9
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.0.0
  dio: ^5.3.2
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.0.1
  meta: ^1.9.1
  mongo_pool: ^1.3.1
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  test: ^1.19.2
